### ISSUE TITLE
Why not use day_map and night_map?

### ISSUE THREAD

**Issue by peteruithoven** [rbunger/Inky-wHAT-Weather-Station#2]
I noticed the `day_map` and `night_map` are not used? Only the `general_map`. Why? There was no solid way to determine night or day? 

I noticed this while converting bits of your approach to a Inky pHat compatible display. I'm going to try to switch to the night map when the current datetime is larger than the sunset datetime.

**Comment by rbunger** [comment]
I have thought about that. Maybe I do not fully understand the concept of day and night maps. I am using the full day prediction (for day and night). Maybe the concept is another one, just switching the icon sets according to current day time...? I will investigate that. Thanks for the hint. It's not problem to determine the time, the "time" module is already imported...

**Comment by peteruithoven** [comment]
I realized later that your focus is a forecast, where you might just show day relevant information. I'm using the icon set more for a current weather indication where it's probably more relevant. 

I also assumed you wrote those lists, but it looks like Erik Flowers did that:  
https://erikflowers.github.io/weather-icons/api-list.html

**Comment by rbunger** [comment]
Yes true I just converted a HTML file from Erik with the mapping to Python. Forgot to mention that.

**Comment by rbunger** [comment]
I have decided to use the day and night icons instead of the general ones I use currently (at the weekend hopefully).

**Comment by rbunger** [comment]
I have updated the code. I'm using day and night icons for the current day and general icons for the other days (forecasts). The code isn't heavily tested (in fact it isn't tested at all).

**Comment by rbunger** [comment]
Seems to work...
