### ISSUE TITLE
License of your code?

### ISSUE THREAD

**Issue by bablokb** [rbunger/Inky-wHAT-Weather-Station#3]
Hi, very nice project. One the to clarify: what is the license of your own code?

**Comment by rbunger** [comment]
Hi, I have written about the licenses for the fonts and icons; my part of the project is completely free. I think I have to read about the different types

**Comment by rbunger** [comment]
Hi, thanks, you are right, I had to read a little about licenses and I have decided for the MIT licence (my code; fonts and icons licences are already specified).
