### ISSUE TITLE
mogrify command

### ISSUE THREAD

**Issue by CrunchCube** [rbunger/Inky-wHAT-Weather-Station#4]
Hi

I'm trying to use the script on my raspberry pi zero but can't run the command: 
mogrify -background white -format PNG8 *.svg

Do you have more information on how to install this library?

**Comment by rbunger** [comment]
Hi,

"mogrify" is part of ImageMagick so you should get it by installing that package...

**Comment by CrunchCube** [comment]
Hi, thank you for answer. Will install that and try again.
